{"name": "Проверяем вход в аккаунт курьера с несуществующим логином", "status": "passed", "start": 1739434178939, "stop": 1739434179154, "uuid": "426a26e2-e2cf-42eb-94fc-0880b2318f54", "historyId": "ac05f8f2b041f62c7727b84aa71195ae", "testCaseId": "ac05f8f2b041f62c7727b84aa71195ae", "fullName": "tests.test_login_courier.TestLoginCourier#test_login_courier_with_wrong_login", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('generate_courier')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "LAPTOP-UNQET23V"}, {"name": "thread", "value": "29312-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}